Fail when tests fail.
Fixes #258.

diff --git a/scripts/tests/Makefile b/scripts/tests/Makefile
--- a/scripts/tests/Makefile
+++ b/scripts/tests/Makefile
@@ -3,17 +3,19 @@ DISTFILES = Makefile $(wildcard *.liq) $(wildcard *.pl)
 top_srcdir = ../..
 include $(top_srcdir)/Makefile.rules
 
+	  # | tee /dev/null - | head -n 1 ; \
+
+	  # if [ $$? -ne 0 ] ; then echo "TEST FAILED" ; echo exit 1 ; fi ; \
+
 test: threesines
 	@for i in $(wildcard *.liq) ; do \
-	  echo -n "$$i... " ; $(top_srcdir)/src/liquidsoap -q ../pervasives.liq - < ./$$i | \
-	  tee /dev/null - | head -n 1 ; \
-	  if [ $$? -ne 0 ] ; then echo FFFFFFFFFFF ; fi ; \
+	  echo -n "$$i... " ; $(top_srcdir)/src/liquidsoap -q ../pervasives.liq - < ./$$i || exit 1 ; \
 	done
 	@echo -n "type_errors.pl... " ; \
 	  if (./type_errors.pl > /dev/null 2> /dev/null) ; then \
 	    echo "TEST PASSED (check manually the prettiness of messages)" ; \
 	  else \
-	    echo "TEST FAILED" ; \
+	    echo "TEST FAILED" ; exit 1 ; \
 	  fi
 
 # Generate samples files in threesines directory
