Cleanup doc & test.

diff --git a/doc/scripts/test_snippets b/doc/scripts/test_snippets
--- a/doc/scripts/test_snippets
+++ b/doc/scripts/test_snippets
@@ -10,9 +10,8 @@ while read i; do
 	BASENAME="`basename $i`"
 	DIRNAME="`dirname $i`"
 	echo -en "Testing \033[1m$BASENAME\033[0m... ";
-	cd "$DIRNAME";
-        if `echo $BYPASS | grep -q "$BASENAME"`; then echo -e "\e[1;34m[bypass]"
-        else ($COMMAND "$BASENAME" > /dev/null 2> /dev/null && echo -e "\e[1;32m[ok]") || echo -e "\e[1;31m[failed]"; 
+        if `echo $BYPASS | grep -q "$BASENAME"`; then echo -e "\033[1;34m[bypass]\033[0m"
+        else ($COMMAND "$i" > /dev/null 2> /dev/null && echo -e "\033[0;32m[ok]\033[0m") || echo -e "\033[0;31m[failed]\033[0m"; 
         fi; 
 	tput sgr0; cd $OLDIR;
 	done
